---
- name: Create directory for Docker Compose configuration.
  file:
    path: "{{ docker_compose_config_dir }}"
    state: directory
    mode: '0755'

- name: "Populate Docker Compose configuration."
  template:
    src: docker-compose.yml.j2
    dest: "{{ docker_compose_config }}"
  notify: restart docker-compose

- name: Configure SWAG for HTTPS.
  template:
    src: site-confs.default.https.j2
    dest: "{{ swag_data }}/nginx/site-confs/default"
  notify: restart swag
  when: wordpress_domain|length > 0

- name: Configure SWAG for HTTP.
  template:
    src: site-confs.default.http.j2
    dest: "{{ swag_data }}/nginx/site-confs/default"
  notify: restart swag
  when: wordpress_domain|length == 0
