---

- name: Create directory for Docker container data.
  file:
    path: "{{ docker_data }}"
    state: directory
    mode: '0755'

- include_tasks: mysql-setup.yml
- include_tasks: wordpress-setup.yml
- include_tasks: swag-setup.yml

- include_tasks: compose.yml

- include_tasks: backup.yml

- name: Configure nightly docker-compose update cron.
  cron:
    minute: "20"
    hour: "2"
    name: docker_compose_pull
    job: |
      cd {{ docker_compose_config_dir }} && /usr/local/bin/docker-compose pull && /usr/local/bin/docker-compose up -d
