---
# Rocket.Chat configuration
# Domain must be a subdomain - the first part will be split off for SWAG config
rocketchat_domain: chat.example.com

# Location for docker-compose configuration
docker_compose_config_dir: /data/docker-compose
docker_compose_config: "{{ docker_compose_config_dir }}/docker-compose.yml"

# Primary mount point for docker data directories
docker_data: /data/docker
# Per-container directories
postgres_data: "{{ docker_data }}/postgres"
wordpress_data: "{{ docker_data }}/wordpress"
swag_data: "{{ docker_data }}/swag"

backup_data: /backup
backup_retention_days: "14"
postgres_backup: "{{ backup_data }}/postgress"
wordpress_backup: "{{ backup_data }}/wordpress"

# Docker image versions
postgres_image_version: alpine
wordpress_image_version: latest
swag_image_version: latest
