---
- name: Update the apt cache if older than an hour.
  apt:
    update_cache: yes
    cache_valid_time: 3600

- include_tasks: python.yml
- include_tasks: fail2ban.yml
- include_tasks: unattended-upgrades.yml

- name: Ensure additional dependencies are installed.
  apt:
    name:
      - ufw
    state: present

- name: Clean up apt.
  apt:
    autoremove: true