---
- name: Ensure Python is installed.
  package:
    name:
      - python3
      - python3-setuptools
      - python3-pip
    state: latest

- name: Ensure pip and setuptools are up to date.
  pip:
    name:
      - pip
      - setuptools
    state: latest
    executable: pip3

- name: Ensure pip_install_packages are installed.
  pip:
    name: "{{ item.name | default(item) }}"
    version: "{{ item.version | default(omit) }}"
    virtualenv: "{{ item.virtualenv | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    executable: pip3
  with_items: "{{ pip_install_packages }}"
